### ISSUE TITLE
Determine magic number for measuring performance increase over time with metrics

### ISSUE THREAD

**Issue by piegarden** [james-cathcart/WorkoutWidget-REST#18]

**Comment by james-cathcart** [comment]
Has this been completed?

**Comment by piegarden** [comment]
This was when we were trying to figure out how to measure progress using weight lifted as a variable when we don't always have the same number of reps in each workout.

We decided to go with the translation formula (converts reps and weight to predicted 1 rep weight) to allow us to mix and match different reps while still getting a consistent output. The plan is to have this in one graph, however I don't know how you plan to address this problem in your other graphs as I am not sure exactly what they are supposed to show. I am excited to see what you have in store though.
