### ISSUE TITLE
Create template to add Workout

### ISSUE THREAD

**Issue by james-cathcart** [james-cathcart/WorkoutWidget-REST#5]

**Comment by piegarden** [comment]
<img width="391" alt="Use-Case Diagram" src="https://user-images.githubusercontent.com/46267375/54866017-ec56d180-4d3c-11e9-8415-debe089f36da.PNG">

**Comment by piegarden** [comment]
<img width="438" alt="Activity diagram -- athlete records the days workout" src="https://user-images.githubusercontent.com/46267375/54866238-5a9c9380-4d3f-11e9-8bcf-c83bb7afba86.PNG">

**Comment by james-cathcart** [comment]
This functionality has moved to the WorkoutWidget-WEB project.
